#!/bin/bash
# ssh-config.sh
# 開発環境から k3s ノードに SSH 接続できるようにする。
#
# 動作:
#  1. 開発環境のグローバル IP を取得
#  2. さくらのクラウドのパケットフィルタに 22/tcp 許可ルールを動的追加
#  3. tfstate から秘密鍵 / ssh config / known_hosts を生成
#
# 使用方法: bash ssh-config.sh [--remove] [--kubeconfig]
#   --remove     SSH 許可ルールを削除してファイアウォールを元に戻す
#   --kubeconfig ~/.kube/config を sv1 から取得・設定する

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TF_DIR="${SCRIPT_DIR}/terraform"
SSH_DIR="${HOME}/.ssh"
KNOWN_HOSTS="${SSH_DIR}/known_hosts"
SSH_CONFIG="${SSH_DIR}/config.d/sakura-k3s"

REMOVE=false
SETUP_KUBECONFIG=false
for arg in "$@"; do
  case "$arg" in
    --remove) REMOVE=true ;;
    --kubeconfig) SETUP_KUBECONFIG=true ;;
  esac
done

# ---------------------------------------------------------------
# Terraform output から必要な情報を取得
# ---------------------------------------------------------------
echo "==> Terraform state から情報を取得中..."
cd "${TF_DIR}"

PACKET_FILTER_ID=$(terraform output -raw packet_filter_id)
NODE_PUBLIC_IPS=$(terraform output -json node_public_ips)
LABEL_PREFIX="${SAKURA_LABEL_PREFIX:-ops-frontier}"

# ---------------------------------------------------------------
# 開発環境のグローバル IP を取得
# ---------------------------------------------------------------
MY_IP=$(curl -sf https://checkip.amazonaws.com | tr -d '[:space:]')
if [[ -z "${MY_IP}" ]]; then
  echo "ERROR: グローバル IP の取得に失敗しました。" >&2
  exit 1
fi
echo "==> 開発環境のグローバル IP: ${MY_IP}"

# ---------------------------------------------------------------
# さくらのクラウド API でパケットフィルタを更新
# ---------------------------------------------------------------
SAKURA_TOKEN="${SAKURA_ACCESS_TOKEN}"
SAKURA_SECRET="${SAKURA_ACCESS_TOKEN_SECRET}"
SAKURA_REGION="${SAKURA_REGION:-is1c}"
API_BASE="https://secure.sakura.ad.jp/cloud/zone/${SAKURA_REGION}/api/cloud/1.1"

get_packet_filter() {
  curl -sf -u "${SAKURA_TOKEN}:${SAKURA_SECRET}" \
    "${API_BASE}/packetfilter/${PACKET_FILTER_ID}"
}

update_packet_filter() {
  local payload="$1"
  curl -sf -X PUT -u "${SAKURA_TOKEN}:${SAKURA_SECRET}" \
    -H "Content-Type: application/json" \
    -d "${payload}" \
    "${API_BASE}/packetfilter/${PACKET_FILTER_ID}"
}

CURRENT_FILTER=$(get_packet_filter)

if $REMOVE; then
  echo "==> SSH 許可ルールを削除中..."
  NEW_EXPRESSIONS=$(echo "${CURRENT_FILTER}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
exprs = data['PacketFilter']['Expression']
exprs = [e for e in exprs if not (e.get('DestinationPort') == '22' and e.get('SourceNetwork', '').endswith('/32'))]
print(json.dumps(exprs))
")
  PAYLOAD=$(echo "${CURRENT_FILTER}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
data['PacketFilter']['Expression'] = json.loads(open('/dev/stdin').read())
print(json.dumps({'PacketFilter': data['PacketFilter']}))
" <<< "${NEW_EXPRESSIONS}")
  update_packet_filter "${PAYLOAD}"
  echo "==> SSH 許可ルールを削除しました。"
  exit 0
fi

echo "==> パケットフィルタに SSH 許可ルールを追加中 (${MY_IP}/32 -> 22/tcp)..."
NEW_EXPRESSIONS=$(echo "${CURRENT_FILTER}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
exprs = data['PacketFilter']['Expression']
# 既存の SSH ルールは削除してから追加 (冪等性)
exprs = [e for e in exprs if not (e.get('DestinationPort') == '22')]
# default deny の前に SSH ルールを挿入
deny_index = next((i for i, e in enumerate(exprs) if not e.get('Action', '') and e.get('Protocol') == 'ip'), len(exprs))
ssh_rule = {
  'Protocol': 'tcp',
  'SourceNetwork': '${MY_IP}/32',
  'DestinationPort': '22',
  'Action': 'allow',
  'Description': 'SSH from dev env (managed by ssh-config.sh)'
}
exprs.insert(deny_index, ssh_rule)
print(json.dumps(exprs))
")
PAYLOAD=$(python3 -c "
import json, sys
current = json.loads(open('/dev/stdin').read())
exprs = json.loads('''${NEW_EXPRESSIONS}''')
current['PacketFilter']['Expression'] = exprs
print(json.dumps({'PacketFilter': current['PacketFilter']}))
" <<< "${CURRENT_FILTER}")
update_packet_filter "${PAYLOAD}" >/dev/null
echo "==> パケットフィルタを更新しました。"

# ---------------------------------------------------------------
# SSH ディレクトリの準備
# ---------------------------------------------------------------
mkdir -p "${SSH_DIR}/config.d"
chmod 700 "${SSH_DIR}"

# 秘密鍵をコピー (Terraform が .ssh/ に生成済み)
PRIVATE_KEY_SRC="${SCRIPT_DIR}/.ssh/id_ed25519"
PRIVATE_KEY_DEST="${SSH_DIR}/id_ed25519_sakura_k3s"
if [[ -f "${PRIVATE_KEY_SRC}" ]]; then
  cp "${PRIVATE_KEY_SRC}" "${PRIVATE_KEY_DEST}"
  chmod 600 "${PRIVATE_KEY_DEST}"
  echo "==> 秘密鍵を ${PRIVATE_KEY_DEST} にコピーしました。"
else
  echo "WARNING: 秘密鍵 ${PRIVATE_KEY_SRC} が見つかりません。terraform apply を先に実行してください。" >&2
fi

# ---------------------------------------------------------------
# SSH config 生成
# ---------------------------------------------------------------
echo "==> SSH config を生成中..."
cat > "${SSH_CONFIG}" <<EOF
# Generated by ssh-config.sh - do not edit manually
EOF

for i in 1 2 3; do
  NODE_NAME="${LABEL_PREFIX}-sv${i}"
  NODE_IP=$(echo "${NODE_PUBLIC_IPS}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['${NODE_NAME}'])" 2>/dev/null || echo "")
  if [[ -z "${NODE_IP}" ]]; then
    continue
  fi
  cat >> "${SSH_CONFIG}" <<EOF

Host ${NODE_NAME}
  HostName ${NODE_IP}
  User core
  IdentityFile ${PRIVATE_KEY_DEST}
  StrictHostKeyChecking no
  UserKnownHostsFile ${KNOWN_HOSTS}
EOF
done

# ~/.ssh/config に Include 追記 (冪等)
INCLUDE_LINE="Include config.d/sakura-k3s"
if ! grep -qF "${INCLUDE_LINE}" "${SSH_DIR}/config" 2>/dev/null; then
  echo -e "${INCLUDE_LINE}\n$(cat "${SSH_DIR}/config" 2>/dev/null || true)" > "${SSH_DIR}/config"
fi
chmod 600 "${SSH_DIR}/config"

echo "==> SSH config を更新しました: ${SSH_CONFIG}"
echo ""
echo "接続例:"
echo "  ssh ${LABEL_PREFIX}-sv1"
echo "  ssh ${LABEL_PREFIX}-sv2"
echo "  ssh ${LABEL_PREFIX}-sv3"

# ---------------------------------------------------------------
# kubeconfig セットアップ (オプション)
# ---------------------------------------------------------------
if $SETUP_KUBECONFIG; then
  echo "==> kubeconfig を ${LABEL_PREFIX}-sv1 から取得中..."
  mkdir -p "${HOME}/.kube"
  SV1_IP=$(echo "${NODE_PUBLIC_IPS}" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d['${LABEL_PREFIX}-sv1'])")
  ssh -i "${PRIVATE_KEY_DEST}" -o StrictHostKeyChecking=no \
    "core@${SV1_IP}" "sudo cat /etc/rancher/k3s/k3s.yaml" \
    | sed "s/127.0.0.1/${SV1_IP}/g" \
    > "${HOME}/.kube/config-sakura-k3s"
  chmod 600 "${HOME}/.kube/config-sakura-k3s"
  export KUBECONFIG="${HOME}/.kube/config-sakura-k3s"
  echo "==> KUBECONFIG=${HOME}/.kube/config-sakura-k3s"
  echo "    次のコマンドを実行してください:"
  echo "    export KUBECONFIG=${HOME}/.kube/config-sakura-k3s"
fi
