#!/bin/bash
set -e

WORKSPACE=/workspaces/sakura-flatcar-k3s-argocd-iac

# ---------------------------------------------------------------
# TF_VAR_ 環境変数を ~/.bashrc に転記
# ---------------------------------------------------------------
cat << 'INNER_EOF' >> ~/.bashrc
# Export TF_VAR_ variables from Codespaces secrets
for var in DO_PAT SAKURA_ACCESS_TOKEN SAKURA_ACCESS_TOKEN_SECRET SAKURA_LABEL_PREFIX SAKURA_REGION SAKURA_SERVER_CPU SAKURA_SERVER_MEMORY SAKURA_SERVER_COMMITMENT SAKURA_SERVER_CPU_MODEL DOMAIN LE_ENVIRONMENT SAKURA_ISO_IMAGE_ID GH_ORGANIZATION GH_CLIENT_ID_GRAFANA GH_CLIENT_SECRET_GRAFANA GH_CLIENT_ID_ARGOCD GH_CLIENT_SECRET_ARGOCD AUTO_SHUTDOWN_UTC; do
    if [ -n "${!var}" ]; then
        export TF_VAR_$(echo "$var" | tr '[:upper:]' '[:lower:]')="${!var}"
    fi
done
INNER_EOF

# ---------------------------------------------------------------
# ansible-playbook aliases を ~/.bashrc に追加
# playbooks/<name>.yml → alias <name>='ansible-playbook ...'
# ---------------------------------------------------------------
cat << INNER_EOF >> ~/.bashrc

# ansible-playbook aliases (generated by post-create.sh)
# ANSIBLE_CONFIG を明示して world-writable 警告を回避する
for playbook in ${WORKSPACE}/ansible/playbooks/*.yml; do
    alias_name=\$(basename -s .yml "\${playbook}")
    alias "\${alias_name}"="(cd ${WORKSPACE}/ansible && ANSIBLE_CONFIG=${WORKSPACE}/ansible/ansible.cfg ansible-playbook playbooks/\${alias_name}.yml)"
done
INNER_EOF

# ---------------------------------------------------------------
# Ansible Python 依存パッケージ
# ---------------------------------------------------------------
echo "==> Ansible 依存パッケージをインストール中..."
pip3 install --quiet ansible-core jinja2 \
    community.general 2>/dev/null || true
# Ansible Galaxy コレクション
ansible-galaxy collection install community.general 2>/dev/null || true

# ---------------------------------------------------------------
# butane インストール
# ---------------------------------------------------------------
BUTANE_VERSION="v0.21.0"
ARCH=$(uname -m)
BUTANE_URL="https://github.com/coreos/butane/releases/download/${BUTANE_VERSION}/butane-${ARCH}-unknown-linux-gnu"
echo "==> butane ${BUTANE_VERSION} をインストール中..."
sudo curl -sfL "${BUTANE_URL}" -o /usr/local/bin/butane
sudo chmod +x /usr/local/bin/butane
butane --version

# ---------------------------------------------------------------
# kubectl インストール
# ---------------------------------------------------------------
KUBECTL_VERSION=$(curl -sfL https://dl.k8s.io/release/stable.txt)
KUBECTL_ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')
echo "==> kubectl ${KUBECTL_VERSION} をインストール中..."
sudo curl -sfL "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/${KUBECTL_ARCH}/kubectl" \
  -o /usr/local/bin/kubectl
sudo chmod +x /usr/local/bin/kubectl
kubectl version --client

# ---------------------------------------------------------------
# helm インストール
# ---------------------------------------------------------------
echo "==> helm をインストール中..."
curl -sfL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
sudo chmod +x /usr/local/bin/helm
helm version

# ---------------------------------------------------------------
# .ssh ディレクトリを作成 (Terraform が秘密鍵を書き込む先)
# ---------------------------------------------------------------
mkdir -p "${WORKSPACE}/.ssh"
chmod 700 "${WORKSPACE}/.ssh"

echo "==> post-create.sh 完了。"
echo "    次のステップ: build-infra または ansible-playbook ansible/playbooks/build-infra.yml"
